import { pageMeta } from '@/lib/metadata'

export const metadata = pageMeta({
  title: 'Privacy Policy',
  description: 'How Cosmonus collects, uses, and protects information across cosmonus.com and StayOnMap.',
  path: '/privacy',
})

export default function PrivacyPage() {
  return (
    <section className="section section--hero">
      <div className="container">
        <div className="page-hero">
          <div className="eyebrow">Legal</div>
          <h1 className="page-hero__title">Privacy Policy</h1>
        </div>

        <div className="legal-layout" style={{ marginTop: 'clamp(2.5rem, 5vw, 4rem)' }}>
          <div className="legal-doc">
          <p className="legal-doc__updated mono">Last updated — January 2026</p>

          <p>
            Cosmonus (&ldquo;we,&rdquo; &ldquo;us&rdquo;) operates cosmonus.com and the products
            built on it, including StayOnMap. This policy explains what information we collect
            and why. Cosmonus is a small, founder-run engineering studio — this document reflects
            that scale honestly rather than describing a data operation we don&apos;t run. It has
            not been reviewed by a lawyer; if you need this to hold up for a specific legal or
            compliance purpose, have counsel review it first.
          </p>

          <h2 id="information-we-collect">Information we collect</h2>
          <p>We collect information directly from you, and, on StayOnMap, information generated by using the product:</p>
          <ul>
            <li>Contact form submissions on cosmonus.com — name, work email, company, and the message you send us</li>
            <li>StayOnMap account information — name, email, phone number, and the details you add to a profile</li>
            <li>StayOnMap listing data — property details, photos, pricing, and availability you post</li>
            <li>StayOnMap messages — conversations between tenants and owners, stored so both sides keep a record</li>
            <li>Basic usage data — your light/dark theme preference, stored locally in your browser, not on our servers</li>
          </ul>

          <h2 id="how-we-use-it">How we use it</h2>
          <p>We use the information above to:</p>
          <ul>
            <li>Reply to messages sent through the contact form</li>
            <li>Operate StayOnMap accounts, listings, and tenant–owner communication</li>
            <li>Run trust and fraud-signal scoring on listings, so risky ones can be reviewed or suspended</li>
            <li>Keep the site and product secure and working as intended</li>
          </ul>
          <p>We do not sell personal data, and we do not use it to build advertising profiles.</p>

          <h2 id="how-we-share-it">How we share it</h2>
          <p>
            We share information only where it&apos;s necessary to run the service: with the
            hosting and database providers that keep cosmonus.com and StayOnMap running, and when
            we&apos;re legally required to disclose it. We do not sell or rent personal data to
            third parties.
          </p>

          <h2 id="data-retention">Data retention</h2>
          <p>
            We keep contact form submissions as long as needed to respond and for a reasonable
            period after, in case you follow up. StayOnMap account, listing, and message data is
            kept for as long as the account is active, and for a limited period after deletion in
            case it&apos;s needed to resolve a dispute or fraud report.
          </p>

          <h2 id="your-rights">Your rights</h2>
          <p>
            You can ask us to access, correct, or delete the personal data we hold about you. To
            do so, email <a href="mailto:hello@cosmonus.com">hello@cosmonus.com</a> from the
            address associated with your data, and we&apos;ll respond within a reasonable time.
          </p>

          <h2 id="cookies-local-storage">Cookies &amp; local storage</h2>
          <p>
            The only thing we store in your browser today is your light/dark theme preference, in
            local storage — not a cookie, not shared with anyone, and not used to track you across
            sites. We don&apos;t currently run third-party analytics or advertising trackers on
            cosmonus.com.
          </p>

          <h2 id="security">Security</h2>
          <p>
            We take reasonable technical steps to protect the data we hold. No system is
            perfectly secure, and we can&apos;t guarantee absolute protection against every
            possible attack — if we become aware of a breach affecting your data, we&apos;ll
            notify you.
          </p>

          <h2 id="changes-to-this-policy">Changes to this policy</h2>
          <p>
            If we change how we handle data in a meaningful way, we&apos;ll update this page and
            change the date above.
          </p>

          <h2 id="contact">Contact</h2>
          <p>
            Questions about this policy: <a href="mailto:hello@cosmonus.com">hello@cosmonus.com</a>.
          </p>
          </div>

          <nav className="legal-toc" aria-label="On this page">
            <p className="legal-toc__head">On this page</p>
            <ul>
              <li><a href="#information-we-collect">Information we collect</a></li>
              <li><a href="#how-we-use-it">How we use it</a></li>
              <li><a href="#how-we-share-it">How we share it</a></li>
              <li><a href="#data-retention">Data retention</a></li>
              <li><a href="#your-rights">Your rights</a></li>
              <li><a href="#cookies-local-storage">Cookies &amp; local storage</a></li>
              <li><a href="#security">Security</a></li>
              <li><a href="#changes-to-this-policy">Changes to this policy</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </section>
  )
}
