import type { Metadata } from "next";
import { site } from "@/lib/site";

/**
 * SEO helpers. Next.js merges `metadata` from layout and page *shallowly*: a page that sets `openGraph` replaces the
 * whole object. So every page builds its complete title / description / canonical / Open Graph / Twitter set here,
 * and none of them inherits the home page's share text by accident. Tags mirror the original cosmonus.com.
 */

/** Share image generated by app/opengraph-image.tsx (1200×630). */
export const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: `${site.name} — ${site.tagline}` };

export function pageMetadata({
  title,
  description,
  path,
  type = "website",
  image,
}: {
  /** Page name; the layout's template adds " — Cosmonus". Omit for the home page. */
  title?: string;
  description: string;
  /** Route path, e.g. "/studio/web". Becomes the canonical URL. */
  path: string;
  type?: "website" | "article";
  /**
   * "fromFile" leaves the share image out, so Next uses the route's own `opengraph-image` file instead —
   * how a blog post gets a share card carrying its own title. Otherwise the site-wide image is used.
   */
  image?: "fromFile";
}): Metadata {
  const shareImages = image === "fromFile" ? {} : { images: [SHARE_IMAGE] };
  const shareTitle = title ? `${title} — ${site.name}` : `${site.name} — ${site.tagline}`;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      siteName: site.name,
      locale: "en_US",
      url: path,
      title: shareTitle,
      description,
      ...shareImages,
    },
    twitter: {
      card: "summary_large_image",
      site: site.twitter,
      creator: site.twitter,
      title: shareTitle,
      description,
      ...(image === "fromFile" ? {} : { images: [SHARE_IMAGE.url] }),
    },
  };
}

/** Organization + WebSite structured data (JSON-LD), as on the original cosmonus.com. */
export function siteJsonLd() {
  const org = `${site.url}/#organization`;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": org,
        name: site.name,
        legalName: site.legal,
        url: site.url,
        logo: `${site.url}/icon.png`,
        description: site.description,
        email: site.contactEmail,
        founder: { "@type": "Person", name: site.founder.name, url: site.founder.url },
        sameAs: site.sameAs,
      },
      {
        "@type": "WebSite",
        "@id": `${site.url}/#website`,
        name: site.name,
        url: site.url,
        description: site.description,
        publisher: { "@id": org },
        inLanguage: "en",
      },
    ],
  };
}

/**
 * BreadcrumbList structured data. Google uses it to show a readable trail ("Cosmonus › Company › Blog")
 * in place of the bare URL, so every page below the top level is worth giving one. Pass the trail without
 * the home page — it is added here.
 */
export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  const items = [{ name: site.name, path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: `${site.url}${item.path === "/" ? "" : item.path}`,
    })),
  };
}

/**
 * FAQPage structured data, for a page that really does carry a list of questions and answers.
 *
 * Items whose answer still holds a `[BRACKETED]` owner placeholder are left out: a placeholder is honest on
 * the page, where a reader can see it is unfilled, but in structured data it is a claim handed to a search
 * engine. Returns null when nothing is left, so a page emits no FAQ data rather than an empty one.
 */
export function faqJsonLd(items: { q: string; a: string }[]) {
  const answered = items.filter((i) => !/\[[A-Z]/.test(i.a));
  if (answered.length === 0) return null;
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: answered.map((i) => ({
      "@type": "Question",
      name: i.q,
      acceptedAnswer: { "@type": "Answer", text: i.a },
    })),
  };
}

