import type { Metadata } from "next";
import { site } from "@/lib/site";

/**
 * SEO helpers. Next.js merges `metadata` from layout and page *shallowly*: a page that sets `openGraph` replaces the
 * whole object. So every page builds its complete title / description / canonical / Open Graph / Twitter set here,
 * and none of them inherits the home page's share text by accident. Tags mirror the original cosmonus.com.
 */

/** Share image generated by app/opengraph-image.tsx (1200×630). */
export const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: `${site.name} — ${site.tagline}` };

export function pageMetadata({
  title,
  description,
  path,
  type = "website",
}: {
  /** Page name; the layout's template adds " — Cosmonus". Omit for the home page. */
  title?: string;
  description: string;
  /** Route path, e.g. "/studio/web". Becomes the canonical URL. */
  path: string;
  type?: "website" | "article";
}): Metadata {
  const shareTitle = title ? `${title} — ${site.name}` : `${site.name} — ${site.tagline}`;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      siteName: site.name,
      locale: "en_US",
      url: path,
      title: shareTitle,
      description,
      images: [SHARE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      site: site.twitter,
      creator: site.twitter,
      title: shareTitle,
      description,
      images: [SHARE_IMAGE.url],
    },
  };
}

/** Organization + WebSite structured data (JSON-LD), as on the original cosmonus.com. */
export function siteJsonLd() {
  const org = `${site.url}/#organization`;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": org,
        name: site.name,
        legalName: site.legal,
        url: site.url,
        logo: `${site.url}/icon.png`,
        description: site.description,
        email: site.contactEmail,
        founder: { "@type": "Person", name: site.founder.name, url: site.founder.url },
        sameAs: site.sameAs,
      },
      {
        "@type": "WebSite",
        "@id": `${site.url}/#website`,
        name: site.name,
        url: site.url,
        description: site.description,
        publisher: { "@id": org },
        inLanguage: "en",
      },
    ],
  };
}
